apiVersion: v1
kind: Service
metadata:
  name: ip-responder
  labels:
    name: ip-responder
spec:
  type: NodePort
  selector:
    app: ip-responder
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
  selector:
    app: ip-responder
  sessionAffinity: None
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-responder
spec:
  selector:
    matchLabels:
      app: ip-responder
  template:
    metadata:
      labels:
        app: ip-responder
    spec:
      containers:
      - name: ip-responder
        image: nginx-ip-responder
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          protocol: TCP
